module.exports = {
  English: [
    'Apple', 'Banana', 'Car', 'Dog', 'Elephant', 'Flower', 'Guitar', 'House', 'Ice Cream', 'Jellyfish',
    'Kangaroo', 'Lemon', 'Mountain', 'Notebook', 'Orange', 'Piano', 'Queen', 'Rocket', 'Sun', 'Tree',
    'Umbrella', 'Violin', 'Whale', 'Xylophone', 'Yo-yo', 'Zebra', 'Airplane', 'Bicycle', 'Camera', 'Dolphin',
    'Egg', 'Frog', 'Grape', 'Hat', 'Igloo', 'Jacket', 'Kite', 'Lion', 'Moon', 'Nest', 'Owl', 'Pencil',
    'Quilt', 'Rabbit', 'Star', 'Tiger', 'Uniform', 'Vase', 'Watch', 'Yacht', 'Anchor', 'Balloon', 'Cloud',
    'Desert', 'Eagle', 'Forest', 'Garden', 'Hammer', 'Island', 'Jewel', 'Key', 'Ladder', 'Magnet', 'Necklace',
    'Ocean', 'Parrot', 'Quiver', 'River', 'Snail', 'Turtle', 'Unicorn', 'Volcano', 'Window', 'X-ray', 'Yawn',
    'Zipper', 'Ant', 'Bear', 'Cat', 'Duck', 'Elm', 'Fish', 'Goat', 'Horse', 'Ink', 'Jar', 'King', 'Leaf',
    'Mouse', 'Net', 'Octopus', 'Pig', 'Quail', 'Rat', 'Snake', 'Toad', 'Under', 'Vest', 'Wolf', 'Yoke',
    'Zero', 'Axe', 'Box', 'Cup', 'Desk', 'Ear', 'Fan', 'Gum', 'Ice', 'Jug', 'Keg', 'Lip', 'Map', 'Nut',
    'Oil', 'Pan', 'Rug', 'Sky', 'Tea', 'Urn', 'Van', 'Wig', 'Yak', 'Zip', 'Ape', 'Bat', 'Cow', 'Dot',
    'Eel', 'Fly', 'Gem', 'Hen', 'Ivy', 'Joy', 'Kit', 'Log', 'Mud', 'Newt', 'Oak', 'Pot', 'Ram', 'Saw',
    'Toy', 'Ufo', 'Vim', 'Web', 'Boxer', 'Crane', 'Drum', 'Easel', 'Flute', 'Globe', 'Harp', 'Iron', 'Joker',
    'Knife', 'Loom', 'Mask', 'Needle', 'Oven', 'Pipe', 'Razor', 'Spoon', 'Telescope', 'Udon', 'Violas', 'Wagon',
    'Amulet', 'Bead', 'Chime', 'Dagger', 'Emblem', 'Flask', 'Gavel', 'Helmet', 'Insignia', 'Javelin', 'Knocker',
    'Lantern', 'Medal', 'Noose', 'Orb', 'Pendant', 'Quill', 'Relic', 'Scepter', 'Trident', 'Urn', 'Vial', 'Wand',
    'Acorn', 'Berry', 'Clover', 'Daisy', 'Fern', 'Grass', 'Holly', 'Iris', 'Juniper', 'Kelp', 'Lily', 'Moss',
    'Nettle', 'Orchid', 'Pollen', 'Reed', 'Seed', 'Thistle', 'Vine', 'Weed', 'Yarrow', 'Zinnia', 'Armadillo',
    'Badger', 'Cheetah', 'Deer', 'Echidna', 'Falcon', 'Giraffe', 'Hyena', 'Iguana', 'Jaguar', 'Koala', 'Leopard',
    'Meerkat', 'Nightingale', 'Ostrich', 'Panther', 'Quokka', 'Raccoon', 'Squirrel', 'Toucan', 'Vulture', 'Walrus',
    'Bagel', 'Cheese', 'Donut', 'Eclair', 'Fudge', 'Garlic', 'Honey', 'Icing', 'Jam', 'Kebab', 'Lollipop', 'Muffin',
    'Noodle', 'Olive', 'Pizza', 'Quiche', 'Ravioli', 'Sushi', 'Taco', 'Udon', 'Vanilla', 'Waffle', 'Yogurt',
    'Abacus', 'Bucket', 'Candle', 'Duster', 'Eraser', 'Folder', 'Goggles', 'Hose', 'Inhaler', 'Joystick', 'Kettle',
    'Lighter', 'Mirror', 'Notebook', 'Outbox', 'Printer', 'Quiver', 'Remote', 'Stapler', 'Tablet', 'Utensil', 'Vacuum',
    'Wallet', 'Albatross', 'Beaver', 'Chameleon', 'Dragonfly', 'Earthworm', 'Flamingo', 'Grasshopper', 'Hummingbird',
    'Impala', 'Jackal', 'Kingfisher', 'Lemur', 'Mongoose', 'Narwhal', 'Otter', 'Platypus', 'Quetzal', 'Salamander',
    'Termite', 'Urchin', 'Wallaby', 'Asparagus', 'Broccoli', 'Cabbage', 'Daikon', 'Eggplant', 'Fennel', 'Ginger',
    'Horseradish', 'Iceberg', 'Jicama', 'Kale', 'Lettuce', 'Mushroom', 'Nori', 'Onion', 'Parsnip', 'Quinoa', 'Radish',
    'Spinach', 'Tomato', 'Ulluco', 'Wasabi', 'Yam', 'Zucchini', 'Aerobics', 'Bowling', 'Cycling', 'Diving', 'Equestrian',
    'Fencing', 'Golf', 'Hiking', 'Ice Hockey', 'Judo', 'Karate', 'Lacrosse', 'Marathon', 'Netball', 'Origami', 'Polo',
    'Quidditch', 'Rugby', 'Surfing', 'Tennis', 'Ultimate', 'Volleyball', 'Wrestling', 'Yoga', 'Zumba'
  ],
  Русский: [
    'Яблоко', 'Банан', 'Машина', 'Собака', 'Слон', 'Цветок', 'Гитара', 'Дом', 'Мороженое', 'Медуза',
    'Кенгуру', 'Лимон', 'Гора', 'Блокнот', 'Апельсин', 'Пианино', 'Королева', 'Ракета', 'Солнце', 'Дерево',
    'Зонт', 'Скрипка', 'Кит', 'Ксилофон', 'Йо-йо', 'Зебра', 'Самолет', 'Велосипед', 'Камера', 'Дельфин',
    'Яйцо', 'Лягушка', 'Виноград', 'Шляпа', 'Иглу', 'Куртка', 'Змей', 'Лев', 'Луна', 'Гнездо', 'Сова', 'Карандаш',
    'Одеяло', 'Кролик', 'Звезда', 'Тигр', 'Форма', 'Ваза', 'Часы', 'Яхта', 'Якорь', 'Шарик', 'Облако',
    'Пустыня', 'Орел', 'Лес', 'Сад', 'Молоток', 'Остров', 'Алмаз', 'Ключ', 'Лестница', 'Магнит', 'Ожерелье',
    'Океан', 'Попугай', 'Колчан', 'Река', 'Улитка', 'Черепаха', 'Единорог', 'Вулкан', 'Окно', 'Рентген', 'Зевота',
    'Молния', 'Муравей', 'Медведь', 'Кот', 'Утка', 'Вяз', 'Рыба', 'Коза', 'Лошадь', 'Чернила', 'Банка', 'Король', 'Лист',
    'Мышь', 'Сеть', 'Осьминог', 'Свинья', 'Перепел', 'Крыса', 'Змея', 'Жаба', 'Под', 'Жилет', 'Волк', 'Ярмо',
    'Ноль', 'Топор', 'Коробка', 'Чашка', 'Стол', 'Ухо', 'Вентилятор', 'Жвачка', 'Лед', 'Кувшин', 'Кег', 'Губа', 'Карта', 'Орех',
    'Масло', 'Сковорода', 'Ковер', 'Небо', 'Чай', 'Урна', 'Фургон', 'Парик', 'Як', 'Молния', 'Обезьяна', 'Летучая мышь', 'Корова', 'Точка',
    'Угорь', 'Муха', 'Драгоценность', 'Курица', 'Плющ', 'Радость', 'Набор', 'Бревно', 'Грязь', 'Тритон', 'Дуб', 'Горшок', 'Баран', 'Пила',
    'Игрушка', 'НЛО', 'Энергия', 'Паутина', 'Боксер', 'Кран', 'Барабан', 'Мольберт', 'Флейта', 'Глобус', 'Арфа', 'Утюг', 'Джокер',
    'Нож', 'Ткацкий станок', 'Маска', 'Игла', 'Печь', 'Труба', 'Бритва', 'Ложка', 'Телескоп', 'Удон', 'Альты', 'Вагон',
    'Амулет', 'Бусина', 'Звон', 'Кинжал', 'Эмблема', 'Колба', 'Молоток', 'Шлем', 'Инсигния', 'Дротик', 'Стук',
    'Фонарь', 'Медаль', 'Петля', 'Сфера', 'Кулон', 'Перо', 'Реликвия', 'Скипетр', 'Трезубец', 'Урна', 'Флакон', 'Палочка',
    'Желудь', 'Ягода', 'Клевер', 'Маргаритка', 'Папоротник', 'Трава', 'Падуб', 'Ирис', 'Можжевельник', 'Ламинария', 'Лилия', 'Мох',
    'Крапива', 'Орхидея', 'Пыльца', 'Тростник', 'Семечко', 'Чертополох', 'Вьюнок', 'Сорняк', 'Тысячелистник', 'Цинния', 'Броненосец',
    'Барсук', 'Гепард', 'Олень', 'Ехидна', 'Сокол', 'Жираф', 'Гиена', 'Игуана', 'Ягуар', 'Коала', 'Леопард',
    'Сурикат', 'Соловей', 'Страус', 'Пантера', 'Квокка', 'Енот', 'Белка', 'Тукан', 'Гриф', 'Морж',
    'Бейгл', 'Сыр', 'Пончик', 'Эклер', 'Помадка', 'Чеснок', 'Мед', 'Глазурь', 'Джем', 'Кебаб', 'Леденец', 'Маффин',
    'Лапша', 'Оливка', 'Пицца', 'Киш', 'Равиоли', 'Суши', 'Тако', 'Удон', 'Ваниль', 'Вафля', 'Йогурт',
    'Абак', 'Ведро', 'Свеча', 'Метелка', 'Ластик', 'Папка', 'Очки', 'Шланг', 'Ингалятор', 'Джойстик', 'Чайник',
    'Зажигалка', 'Зеркало', 'Блокнот', 'Исходящие', 'Принтер', 'Колчан', 'Пульт', 'Степлер', 'Планшет', 'Утварь', 'Пылесос',
    'Кошелек', 'Альбатрос', 'Бобер', 'Хамелеон', 'Стрекоза', 'Червь', 'Фламинго', 'Кузнечик', 'Колибри',
    'Импала', 'Шакал', 'Зимородок', 'Лемур', 'Мангуст', 'Нарвал', 'Выдра', 'Утконос', 'Кетцаль', 'Саламандра',
    'Термит', 'Еж', 'Валлаби', 'Спаржа', 'Брокколи', 'Капуста', 'Дайкон', 'Баклажан', 'Фенхель', 'Имбирь',
    'Хрен', 'Айсберг', 'Хикама', 'Капуста', 'Салат', 'Гриб', 'Нори', 'Лук', 'Пастернак', 'Киноа', 'Редис',
    'Шпинат', 'Томат', 'Уллюко', 'Васаби', 'Ямс', 'Цукини', 'Аэробика', 'Боулинг', 'Велоспорт', 'Дайвинг', 'Конный спорт',
    'Фехтование', 'Гольф', 'Пеший туризм', 'Хоккей', 'Дзюдо', 'Каратэ', 'Лакросс', 'Марафон', 'Нетбол', 'Оригами', 'Поло',
    'Квиддич', 'Регби', 'Серфинг', 'Теннис', 'Алтимат', 'Волейбол', 'Борьба', 'Йога', 'Зумба'
  ]
};